# Generated by Django 3.1.7 on 2021-04-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Sampark', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userDetails',
            new_name='userDetail',
        ),
    ]
